url: 
baseurl: 

# Site settings
title: Neodelphis
email: contac@neodelphis.com
description: "Faisons de l'IA votre meilleur atout concurrentiel."


# Team names, titles and social links
people:
- name: Pierre Jaumier
  pic: 1
  position: Data Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pierre-jaumier-646785177/
    - title: github
      url: https://github.com/neodelphis

  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/neodelphis
  - title: linkedin
    url: https://www.linkedin.com/in/pierre-jaumier-646785177/
# Postal address (add as many lines as necessary)
address:
  - line: Les Sables d'Olonne
  - line: France

# Build settings
markdown: kramdown
permalink: pretty