# L'URL complète de votre site en production. Essentiel pour les plugins comme jekyll-seo-tag.
url: "https://www.neodelphis.com"
# Laissez vide si votre site est à la racine du domaine.
baseurl: ""

# Site settings
title: Neodelphis
email: contac@neodelphis.com
description: "Faisons de l'IA votre meilleur atout concurrentiel."


# Team names, titles and social links
people:
- name: Pierre Jaumier
  pic: 1
  position: Lead Developer & Data Scientist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pierre-jaumier-646785177/
    - title: github
      url: https://github.com/neodelphis

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/neodelphis
  - title: linkedin
    url: https://www.linkedin.com/in/pierre-jaumier-646785177/
# Postal address (add as many lines as necessary)
address:
  - line: Les Sables d'Olonne
  - line: France

# Build settings
markdown: kramdown
permalink: pretty