services:
  website:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: neodelphis_website_prod
    restart: always
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true