services:
  website-dev:
    # On se base sur le Dockerfile existant, mais on s'arrête à l'étape "builder"
    # qui contient l'environnement Ruby et les dépendances.
    build:
      context: .
      target: builder
    # On monte le répertoire courant dans le conteneur pour voir les changements en direct.
    # Le chemin doit correspondre au WORKDIR de l'image de base (`/srv/jekyll`).
    volumes:
      - .:/srv/jekyll
      # On utilise un volume pour garder le cache des gems et accélérer les lancements.
      - gem_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    # Utiliser "bundle exec" est une bonne pratique pour s'assurer que la version
    # de Jekyll définie dans le Gemfile.lock est bien celle qui est utilisée.
    command: bundle exec jekyll serve --watch --force_polling --host 0.0.0.0

volumes:
  gem_cache:
