services:
  website-dev:
    # On se base sur le Dockerfile existant, mais on s'arrête à l'étape "builder"
    # qui contient l'environnement Ruby et les dépendances.
    build:
      context: .
      target: builder
    # On monte le répertoire courant dans le conteneur pour voir les changements en direct.
    volumes:
      - .:/usr/src/app
      # On utilise un volume pour garder le cache des gems et accélérer les lancements.
      - gem_cache:/usr/local/bundle
    ports:
      - "4000:4000"
    # La commande se concentre sur le lancement du serveur.
    # L'installation des gems est gérée lors du build de l'image.
    # Si vous modifiez votre Gemfile, il suffira de lancer `docker compose build`.
    command: jekyll serve --watch --force_polling --host 0.0.0.0

volumes:
  gem_cache:
