services:
  website:
    # Construit l'image en utilisant le Dockerfile à la racine du projet.
    build: .
    container_name: neodelphis_website_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-data:/etc/letsencrypt

volumes:
  certbot-data:
